# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build C# .NET Solution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore 
      working-directory: csharp/solution_and_tests
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: csharp/solution_and_tests
    - name: Test
      run: dotnet test ./solution_and_tests.sln  --no-build --verbosity normal
      working-directory: csharp
